apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: inventory-app
spec:
  template:
    spec:
      containers:
        - name: backend
          imagePullPolicy: IfNotPresent
